services:
  argo-db:
    image: postgres:14.4
    environment:
      - POSTGRES_USER=postgres  # name of the application database user
      - POSTGRES_PASSWORD=postgres  # name of the application database user
      - POSTGRES_DB=postgres  # name of the application database
    volumes:
      - argodbvolume:/var/lib/postgresql/data/
  argo-web:
    build: .
    entrypoint: /code/entrypoint.sh
    environment:
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_STATIC_URL=${DJANGO_STATIC_URL}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
      - ELASTICSEARCH_INDEX=${ELASTICSEARCH_INDEX}
      - ELASTICSEARCH_CONNECTION=${ELASTICSEARCH_CONNECTION}
      - ELASTICSEARCH_API_KEY=${ELASTICSEARCH_API_KEY}
      - SQL_ENGINE=${SQL_ENGINE}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_HOST=${SQL_HOST}
      - SQL_PORT=${SQL_PORT}
      - USE_X_FORWARDED_HOST=${USE_X_FORWARDED_HOST}
      - SECURE_PROXY_SSL_HEADER=${SECURE_PROXY_SSL_HEADER}
      - CITATION_REPOSITORY_NAME=${CITATION_REPOSITORY_NAME}
      - CITATION_REPOSITORY_BASEURL=${CITATION_REPOSITORY_BASEURL}
      - CITATION_SEPARATOR=${CITATION_SEPARATOR}
    volumes:
      - .:/code
    ports:
      - "${APPLICATION_PORT:-8014}:${APPLICATION_PORT:-8014}"
    depends_on:
      - argo-db

  elasticsearch:
    image: elasticsearch:7.17.25
    environment:
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:8000
      - http.cors.allow-headers=Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With
      - http.cors.allow-credentials=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  argodbvolume:
  elasticsearch:
